/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/mapping/owners': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
         * Query owner mappings
         * @description Retrieve provisioned owner mappings, optionally filtered by finId list.
         */
    get: operations['getOwnerMappings'];
    put?: never;
    /**
         * Create, update, or delete owner mapping
         * @description Associate a FinP2P finId with ledger-specific account identifiers. Setting status to "inactive" deletes the mapping.
         */
    post: operations['createOwnerMapping'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mapping/fields': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
         * Get supported account mapping fields
         * @description Returns metadata describing the structure of account mapping fields.
         */
    get: operations['getMappingFields'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mapping/networks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
         * Query network mappings
         * @description Retrieve registered network mappings, optionally filtered by networkId list.
         */
    get: operations['getNetworkMappings'];
    put?: never;
    /**
         * Create, update, or delete network mapping
         * @description Register or update a network execution environment. Setting status to "inactive" deletes the mapping.
         */
    post: operations['createNetworkMapping'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mapping/network-fields': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
         * Get supported network mapping fields
         * @description Returns metadata describing the network mapping fields supported by this adapter.
         */
    get: operations['getNetworkMappingFields'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Key-value pairs of adapter-specific account identifiers (e.g. ledgerAccountId, custodyAccountId) */
    accountMappings: {
      [key: string]: string;
    };
    /** @description Key-value pairs of adapter-specific network configuration (e.g. chainId, rpcUrl, submitMode) */
    networkMappings: {
      [key: string]: string;
    };
    ownerMapping: {
      /** @description FinP2P identity (hex secp256k1 compressed public key) */
      finId: string;
      accountMappings: components['schemas']['accountMappings'];
    };
    networkMapping: {
      /** @description Stable network identifier (e.g. eip155:1, besu:corp-settlement) */
      networkId: string;
      networkMappings: components['schemas']['networkMappings'];
    };
    createOwnerMappingRequest: {
      /** @description FinP2P identity (hex secp256k1 compressed public key) */
      finId: string;
      /**
             * @description Set to "inactive" to delete the mapping
             * @default active
             * @enum {string}
             */
      status: 'active' | 'inactive';
      accountMappings: components['schemas']['accountMappings'];
    };
    createOwnerMappingResponse: components['schemas']['ownerMapping'] & {
      /** @description Contract ID of the on-ledger FinID credential (or "none") */
      credentialCid?: string;
      /** @description Status of on-ledger credential provisioning (e.g. "created", "existing", "skipped") */
      credentialStatus?: string;
    };
    createNetworkMappingRequest: {
      /** @description Stable network identifier (e.g. eip155:1, besu:corp-settlement) */
      networkId: string;
      /**
             * @description Set to "inactive" to delete the mapping
             * @default active
             * @enum {string}
             */
      status: 'active' | 'inactive';
      networkMappings: components['schemas']['networkMappings'];
    };
    mappingField: {
      /** @description The field name within the mapping */
      field: string;
      /** @description Human-readable description of the field */
      description: string;
      /** @description Example value for the field */
      exampleValue: string;
    };
    errorResponse: {
      /** @description Error message */
      error: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getOwnerMappings: {
    parameters: {
      query?: {
        /** @description Comma-separated list of finIds to filter by */
        finIds?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of owner mappings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ownerMapping'][];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['errorResponse'];
        };
      };
    };
  };
  createOwnerMapping: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['createOwnerMappingRequest'];
      };
    };
    responses: {
      /** @description Mapping created, updated, or deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['createOwnerMappingResponse'];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['errorResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['errorResponse'];
        };
      };
    };
  };
  getMappingFields: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of account mapping field descriptors */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['mappingField'][];
        };
      };
    };
  };
  getNetworkMappings: {
    parameters: {
      query?: {
        /** @description Comma-separated list of networkIds to filter by */
        networkIds?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of network mappings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['networkMapping'][];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['errorResponse'];
        };
      };
    };
  };
  createNetworkMapping: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['createNetworkMappingRequest'];
      };
    };
    responses: {
      /** @description Network mapping created, updated, or deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['networkMapping'];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['errorResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['errorResponse'];
        };
      };
    };
  };
  getNetworkMappingFields: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of network mapping field descriptors */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['mappingField'][];
        };
      };
    };
  };
}
