/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/mapping/owners': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
         * Query owner mappings
         * @description Retrieve provisioned owner mappings, optionally filtered by finId list.
         */
    get: operations['getOwnerMappings'];
    put?: never;
    /**
         * Create or update owner mapping
         * @description Associate a FinP2P finId with a ledger-specific account identifier. Also provisions an on-ledger credential when possible.
         */
    post: operations['createOwnerMapping'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/mapping/fields': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
         * Get supported account mapping fields
         * @description Returns metadata describing the structure of account mapping fields.
         */
    get: operations['getMappingFields'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    ownerStatus: 'active' | 'inactive';
    accountMappings: {
      /** @description Ledger-specific account identifier for the holder (e.g. Canton party ID "auth0_00abc123::1220def456...") */
      ledgerAccountId: string;
    };
    ownerMapping: {
      /** @description FinP2P identity (hex secp256k1 compressed public key) */
      finId: string;
      status: components['schemas']['ownerStatus'];
      accountMappings: components['schemas']['accountMappings'];
    };
    createOwnerMappingRequest: {
      /** @description FinP2P identity (hex secp256k1 compressed public key) */
      finId: string;
      status?: components['schemas']['ownerStatus'];
      accountMappings: components['schemas']['accountMappings'];
    };
    createOwnerMappingResponse: components['schemas']['ownerMapping'] & {
      /** @description Contract ID of the on-ledger FinID credential (or "none") */
      credentialCid?: string;
      /** @description Status of on-ledger credential provisioning (e.g. "created", "existing", "skipped") */
      credentialStatus?: string;
    };
    accountMappingField: {
      /** @description The field name within accountMappings */
      field: string;
      /** @description Human-readable description of the field */
      description: string;
      /** @description Example value for the field */
      exampleValue: string;
    };
    errorResponse: {
      /** @description Error message */
      error: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getOwnerMappings: {
    parameters: {
      query?: {
        /** @description Comma-separated list of finIds to filter by */
        finIds?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of owner mappings */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ownerMapping'][];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['errorResponse'];
        };
      };
    };
  };
  createOwnerMapping: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['createOwnerMappingRequest'];
      };
    };
    responses: {
      /** @description Mapping created or updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['createOwnerMappingResponse'];
        };
      };
      /** @description Invalid request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['errorResponse'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['errorResponse'];
        };
      };
    };
  };
  getMappingFields: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of account mapping field descriptors */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['accountMappingField'][];
        };
      };
    };
  };
}
