/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/** Extracted recursive types to break circular references in generated schemas */
export type RecursiveEIP712TypedValue = (string) | (number) | (boolean) | (string) | RecursiveEIP712TypeObject | RecursiveEIP712TypeArray;
export type RecursiveEIP712TypeObject = {
            [key: string]: RecursiveEIP712TypedValue;
        };
export type RecursiveEIP712TypeArray = RecursiveEIP712TypedValue[];
export interface paths {
    "/plan/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve execution plan
         * @description Expects a ledger to approve the upcoming execution plan
         */
        post: operations["approveExecutionPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/proposal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a plan proposal plan
         * @description Request adapter approval or rejection to a proposal in an execution plan
         */
        post: operations["executionPlanProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/proposal/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify the adapter on the agreement status (Approve/Rejected) for a specific proposal
         * @description notify the adapter on proposal status
         */
        post: operations["executionPlanProposalStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/depositInstruction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deposit instruction
         * @description Create a deposit instruction for an owner
         */
        post: operations["depositInstruction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/payout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Payout request
         * @description Payout owner assets to external destination
         */
        post: operations["payout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/getBalance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get asset balance
         * @deprecated
         * @description Get asset balance for specified owner
         */
        post: operations["getAssetBalance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create asset
         * @description Create a new asset
         */
        post: operations["createAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue asset token
         * @description Issue specified amount of asset tokens for the owner
         */
        post: operations["issueAssets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Asset Token Redeem
         * @description Redeem existing asset token for new owner. Redeem of ownership is done by eliminating existing tokens owned by the owner.
         */
        post: operations["redeemAssets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Asset Token Move
         * @description Move existing asset token to another ledger
         */
        post: operations["moveAssets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Asset Token Transfer
         * @description Transfer existing asset token to a new owner. Transfer of ownership is done by eliminating existing tokens owned by the sender and creating new tokens with the new owner.
         */
        post: operations["transferAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or bind an investor account on this LA (Phase 1)
         * @description Single LA-side endpoint covering both flows:
         *
         *     - **Create new** — `bindInfo` is absent. The LA generates a fresh wallet on the
         *       asset's network.
         *     - **Bind existing** — `bindInfo` carries the caller-supplied `networkAccount`
         *       and `ownershipSignature` (proof-of-ownership hint).
         *
         *     The LA issues a **challenge** (signatureTemplate / walletConnect / deposit /
         *     fireblocksApproval / …) which the user must fulfill. Two response shapes:
         *
         *     - `207 Multi-Status` — challenge ready immediately; body has `challenge` and
         *       `operationResponseStrategy`.
         *     - `202 Accepted` — LA needs more time; body has `cid` and
         *       `operationResponseStrategy`. Asset node polls or awaits callback per strategy;
         *       the challenge arrives via `GET /operations/status/{cid}`.
         *
         *     The `ledger.accounts.wallets` jsonb column is updated **only after challenge verification**.
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{cid}/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit signature proof for a signatureTemplate challenge (Phase 1)
         * @description Used only when the challenge `type` is `signatureTemplate`. The asset node forwards
         *     the client's signature; the LA verifies it against the challenge payload. Verification
         *     outcome is reported via the workflow's normal response strategy.
         */
        post: operations["submitAccountProof"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unbind an investor account (Phase 1)
         * @description Removes the account entry from the `ledger.accounts.wallets` jsonb column. Async; cid in response.
         */
        delete: operations["removeAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/receipts/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Receipt
         * @description Get asset transaction receipt
         */
        get: operations["getReceipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hold Asset
         * @description Hold the owner asset
         */
        post: operations["holdOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Release Asset
         * @description Release held assets
         */
        post: operations["releaseOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rollback held asset
         * @description Release back held asset to the owner
         */
        post: operations["rollbackOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/status/{cid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operation Status
         * @description Get the operation status by an operation correlation id
         */
        get: operations["getOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/asset/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get asset balance information
         * @description Get asset balance information for finId
         */
        post: operations["GetAssetBalanceInfo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the service.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DepositInstructionRequest: {
            destination: components["schemas"]["depositPayoutAccount"];
            owner: components["schemas"]["depositPayoutAccount"];
            asset: components["schemas"]["depositAsset"];
            /** @description Amount to deposit */
            amount?: string;
            details?: Record<string, never>;
            nonce?: components["schemas"]["nonce"];
            signature?: components["schemas"]["signature"];
        };
        DepositInstructionResponse: components["schemas"]["depositOperation"];
        PayoutRequest: {
            source: components["schemas"]["depositPayoutAccount"];
            destination?: components["schemas"]["depositPayoutAccount"];
            /** @description How many units of the asset */
            quantity: string;
            payoutInstruction?: components["schemas"]["payoutInstruction"];
            asset: components["schemas"]["finp2pAsset"];
            nonce?: components["schemas"]["nonce"];
            signature?: components["schemas"]["signature"];
        };
        PayoutResponse: components["schemas"]["receiptOperation"];
        GetAssetBalanceRequest: {
            owner: components["schemas"]["account"];
        };
        GetAssetBalanceResponse: components["schemas"]["balance"];
        CreateAssetRequest: {
            /** @description The asset metadata */
            metadata?: {
                [key: string]: unknown;
            };
            asset: components["schemas"]["finp2pAssetBase"];
            ledgerAssetBinding?: components["schemas"]["ledgerAssetIdentifier"];
            name?: components["schemas"]["assetName"];
            issuerId?: components["schemas"]["ownerResourceId"];
            denomination?: components["schemas"]["assetDenomination"];
        };
        CreateAssetResponse: components["schemas"]["OperationBase"] & {
            error?: components["schemas"]["createAssetOperationErrorInformation"];
            response?: components["schemas"]["assetCreateResponse"];
        };
        IssueAssetsRequest: {
            nonce: components["schemas"]["nonce"];
            destination: components["schemas"]["account"];
            /** @description How many units of the asset tokens */
            quantity: string;
            /** @description Reference to the corresponding settlement operation */
            settlementRef: string;
            signature: components["schemas"]["signature"];
            executionContext?: components["schemas"]["executionContext"];
        };
        IssueAssetsResponse: components["schemas"]["receiptOperation"];
        RedeemAssetsRequest: {
            nonce: components["schemas"]["nonce"];
            operationId?: string;
            source: components["schemas"]["account"];
            /** @description How many units of the asset tokens */
            quantity: string;
            /** @description Reference to the corresponding payment operation */
            settlementRef: string;
            signature: components["schemas"]["signature"];
            executionContext?: components["schemas"]["executionContext"];
        };
        RedeemAssetsResponse: components["schemas"]["receiptOperation"];
        TransferAssetRequest: {
            nonce: components["schemas"]["nonce"];
            source: components["schemas"]["account"];
            destination: components["schemas"]["account"];
            /** @description How many units of the asset tokens */
            quantity: string;
            /** @description Reference to the corresponding payment operation */
            settlementRef: string;
            signature: components["schemas"]["signature"];
            executionContext?: components["schemas"]["executionContext"];
        };
        TransferAssetResponse: components["schemas"]["receiptOperation"];
        MoveAssetsRequest: {
            nonce: components["schemas"]["nonce"];
            operationId?: string;
            source: components["schemas"]["account"];
            destination: components["schemas"]["account"];
            /** @description How many units of the asset tokens */
            quantity: string;
            signature: components["schemas"]["signature"];
            executionContext?: components["schemas"]["executionContext"];
        };
        MoveAssetsResponse: components["schemas"]["receiptOperation"];
        GetReceiptResponse: components["schemas"]["receiptOperation"];
        HoldOperationRequest: {
            nonce: components["schemas"]["nonce"];
            /** @description A unique operation ID assigned to the hold request, used to track and reference the asset for future release or rollback actions */
            operationId: string;
            source: components["schemas"]["account"];
            destination?: components["schemas"]["account"];
            /** @description How many units of the asset tokens */
            quantity: string;
            /**
             * Format: uint64
             * @description ttl expiry value indicating the escrow hold time limitation
             */
            expiry: number;
            signature: components["schemas"]["signature"];
            executionContext?: components["schemas"]["executionContext"];
        };
        HoldOperationResponse: components["schemas"]["receiptOperation"];
        ReleaseOperationRequest: {
            /** @description The operation ID from the hold request, required to authorize the asset release */
            operationId: string;
            source: components["schemas"]["account"];
            destination: components["schemas"]["account"];
            /** @description How many units of the asset tokens */
            quantity: string;
            executionContext?: components["schemas"]["executionContext"];
        };
        ReleaseOperationResponse: components["schemas"]["receiptOperation"];
        RollbackOperationRequest: {
            /** @description The operation ID from the hold request, required to revert the asset hold */
            operationId: string;
            source: components["schemas"]["account"];
            /** @description How many units of the asset tokens */
            quantity: string;
            executionContext?: components["schemas"]["executionContext"];
        };
        RollbackOperationResponse: components["schemas"]["receiptOperation"];
        GetOperationStatusRequest: {
            /** @description correlation id of an operation */
            cid?: string;
        };
        GetOperationStatusResponse: components["schemas"]["operationStatus"];
        depositInstruction: {
            account: components["schemas"]["depositPayoutAccount"];
            asset?: components["schemas"]["depositAsset"];
            /** @description Instructions for the deposit operation */
            description?: string;
            paymentOptions?: components["schemas"]["paymentMethods"];
            /**
             * @deprecated
             * @description Any addition deposit specific information, deprecated use "payment method options" instead fields
             */
            details?: Record<string, never>;
            /** @description operation id reference while will correlate with any receipt associated with the deposit operation */
            operationId?: string;
        };
        asset: {
            ledgerIdentifier: components["schemas"]["ledgerAssetIdentifier"];
        } & components["schemas"]["finp2pAssetBase"];
        payoutAsset: components["schemas"]["finp2pAsset"];
        payoutInstruction: {
            /** @description withdrawal description */
            description: string;
        };
        account: {
            asset: components["schemas"]["asset"];
            finId: components["schemas"]["finId"];
            ledgerAccount?: components["schemas"]["walletAccount"] | components["schemas"]["caip10Account"] | components["schemas"]["custodialAccount"];
        };
        walletLedgerAccount: components["schemas"]["walletAccount"];
        caip10LedgerAccount: components["schemas"]["caip10Account"];
        custodialLedgerAccount: components["schemas"]["custodialAccount"];
        depositPayoutAccount: {
            finId: components["schemas"]["finId"];
            account: components["schemas"]["finIdAccountBase"];
        };
        finIdAccountBase: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "finId";
            finId: components["schemas"]["finId"];
        };
        balance: {
            asset: components["schemas"]["asset"];
            /** @description the number of asset tokens */
            balance: string;
        };
        receiptOperation: components["schemas"]["OperationBase"] & {
            error?: components["schemas"]["receiptOperationErrorInformation"];
            response?: components["schemas"]["receipt"];
        };
        /**
         * @description Body for `POST /accounts/create`. Single LA-side endpoint covering both create-new
         *     and bind-existing flows.
         *
         *     - **Create new** — omit `bindInfo`. The LA generates a wallet on the asset's network.
         *     - **Bind existing** — populate `bindInfo` with the caller-supplied wallet and a
         *       proof-of-ownership signature hint. The LA still issues a challenge for final verification.
         *
         *     The response is either `207` (challenge ready) or `202` (challenge pending) — see the
         *     endpoint definition.
         */
        CreateAccountRequest: {
            organizationId: string;
            assetId: string;
            /**
             * @description The investor this account is being onboarded for, identified by their canonical
             *     finId (hex-encoded compressed secp256k1 public key — the same identity that appears
             *     on this investor's ledger operation legs). Resolved by the asset node from the
             *     investor profile; lets the ledger adapter couple the resulting network account to
             *     the investor so it can enforce wallet↔finId ownership on later operations. Required:
             *     an investor without a resolvable finId cannot onboard a network account.
             */
            finId: components["schemas"]["finId"];
            bindInfo?: components["schemas"]["BindInfo"];
        };
        /** @description Bind-info block. When present in `CreateAccountRequest`, signals the bind-existing flow. */
        BindInfo: {
            networkAccount: components["schemas"]["networkAccount"];
            /**
             * @description Proof-of-ownership hint over the network account. The LA may verify this upfront,
             *     but the authoritative ownership proof is the challenge-fulfillment step.
             */
            ownershipSignature: components["schemas"]["signature"];
        };
        /** @description Body for `POST /accounts/{cid}/proof`. Used only for `signatureTemplate` challenges. */
        SubmitAccountProofRequest: {
            /** @description Signature over the LA's `signatureTemplate` challenge payload. */
            ownershipSignature: components["schemas"]["signature"];
        };
        /**
         * @description Returned for `202` and for `200` from `proof` / `delete`. When `isCompleted` is
         *     false, the result is not yet available and `cid` lets the asset node poll
         *     `/operations/status/{cid}` or receive a callback per `operationResponseStrategy`.
         *     When the adapter completes the operation synchronously, `isCompleted` is true and
         *     exactly one of `response` (the account it created) or `error` is present.
         */
        AccountOperationAccepted: components["schemas"]["OperationBase"] & {
            operationMetadata?: components["schemas"]["OperationMetadata"];
            response?: components["schemas"]["networkAccountRecord"];
            error?: components["schemas"]["networkAccountOperationErrorInformation"];
            /**
             * Format: int64
             * @description Onboarding deadline the ledger adapter grants for this create/bind, in
             *     seconds from now. The asset node arms the workflow's whole-process timeout
             *     from this value (set once, at acceptance). Omitted/zero => no auto-expiry.
             */
            expiresInSeconds?: number;
        };
        /**
         * @description Returned for `207` from `POST /accounts/create`. Structurally a superset of
         *     AccountOperationAccepted (the router decodes both create responses into this
         *     one type), adding the LA-issued challenge.
         */
        AccountOperationChallenge: components["schemas"]["AccountOperationAccepted"] & {
            challenge: components["schemas"]["AccountChallenge"];
        };
        /**
         * @description LA-issued challenge that the user must fulfill. Discriminated by `type`. New variants
         *     can be added without breaking existing clients.
         */
        AccountChallenge: components["schemas"]["AccountChallengeWalletConnect"] | components["schemas"]["AccountChallengeSignatureTemplate"] | components["schemas"]["AccountChallengeDeposit"] | components["schemas"]["AccountChallengeFireblocksApproval"];
        AccountChallengeWalletConnect: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "walletConnect";
            /** @description WalletConnect URI or QR-encodable payload. */
            uri: string;
        };
        AccountChallengeSignatureTemplate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "signatureTemplate";
            /**
             * @description Hex-encoded data the client must sign with the wallet's private key and submit via
             *     `POST /accounts/{cid}/proof`.
             */
            payload: string;
        };
        AccountChallengeDeposit: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "deposit";
            /** @description Address claimed by the user. */
            fromAddress: string;
            /** @description Destination address the LA watches. */
            toAddress: string;
            /** @description Required deposit amount (string for precision). */
            amount: string;
        };
        AccountChallengeFireblocksApproval: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "fireblocksApproval";
            /** @description Fireblocks-side request id; user approves in the Fireblocks app. */
            fireblocksRequestId: string;
        };
        /** @description Canonical account record returned on workflow completion via `GET /operations/status/{cid}`. */
        networkAccountRecord: {
            /** @description LA-assigned account identifier. */
            id: string;
            networkAccount: components["schemas"]["networkAccount"];
        };
        createAssetOperation: components["schemas"]["OperationBase"] & {
            error?: components["schemas"]["createAssetOperationErrorInformation"];
            response?: components["schemas"]["assetCreateResponse"];
        };
        assetCreateResponse: {
            ledgerAssetInfo: components["schemas"]["ledgerAssetInfo"];
        };
        depositOperation: components["schemas"]["OperationBase"] & {
            error?: components["schemas"]["depositOperationErrorInformation"];
            response?: components["schemas"]["depositInstruction"];
        };
        depositOperationErrorInformation: {
            /**
             * Format: uint32
             * @description 1 for failure in regApps validation, 4 failure in signature verification
             */
            code?: number;
            message?: string;
            regulationErrorDetails?: components["schemas"]["RegulationError"][];
        };
        createAssetOperationErrorInformation: {
            /** Format: uint32 */
            code?: number;
            message?: string;
        };
        receiptOperationErrorInformation: {
            /**
             * Format: uint32
             * @description 1 for failure in regApps validation, 4 failure in signature verification
             */
            code: number;
            message: string;
            regulationErrorDetails?: components["schemas"]["RegulationError"][];
        };
        executionOperationErrorInformation: Record<string, never>;
        executionContext: {
            /** @description execution plan id */
            executionPlanId: string;
            /**
             * Format: uint32
             * @description execution instruction sequence number
             */
            instructionSequenceNumber: number;
        };
        operationStatus: components["schemas"]["operationStatusCreateAsset"] | components["schemas"]["operationStatusDeposit"] | components["schemas"]["operationStatusReceipt"] | components["schemas"]["operationStatusApproval"] | components["schemas"]["operationStatusAccount"];
        operationStatusCreateAsset: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "createAsset";
            operation: components["schemas"]["createAssetOperation"];
        };
        operationStatusDeposit: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "deposit";
            operation: components["schemas"]["depositOperation"];
        };
        operationStatusReceipt: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "receipt";
            operation: components["schemas"]["receiptOperation"];
        };
        operationStatusApproval: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "approval";
            operation: components["schemas"]["ExecutionPlanApprovalOperation"];
        };
        operationStatusAccount: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "account";
            operation: components["schemas"]["networkAccountOperation"];
        };
        /**
         * @description Status of an investor network-account create/bind/unbind operation, polled via
         *     `GET /operations/status/{cid}`. While a challenge is outstanding, `challenge` is
         *     present; on completion `response` carries the canonical `{ id, wallet }`; on failure
         *     `error` carries the LA-level code/message.
         */
        networkAccountOperation: components["schemas"]["OperationBase"] & {
            challenge?: components["schemas"]["AccountChallenge"];
            response?: components["schemas"]["networkAccountRecord"];
            error?: components["schemas"]["networkAccountOperationErrorInformation"];
            /**
             * Format: int64
             * @description Onboarding deadline the ledger adapter grants, in seconds from now, when it
             *     supplies (or revises) one on this status — e.g. alongside a challenge delivered
             *     via callback in proxy mode, where the adapter's own deadline could not ride the
             *     proxy's immediate acceptance. The asset node re-arms the workflow deadline from
             *     a non-zero value. Omitted/zero => previously armed deadline stands.
             */
            expiresInSeconds?: number;
        };
        networkAccountOperationErrorInformation: {
            /** Format: uint32 */
            code: number;
            message: string;
        };
        /** @description represent a signature template information */
        signature: {
            /** @description hex representation of the signature */
            signature: string;
            template: components["schemas"]["signatureTemplate"];
            hashFunc: components["schemas"]["hashFunction"];
        };
        signatureTemplate: components["schemas"]["hashListTemplate"] | components["schemas"]["EIP712Template"];
        /** @description ordered list of hash groups */
        hashListTemplate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "hashList";
            hashGroups: components["schemas"]["hashGroup"][];
            /** @description hex representation of the combined hash groups hash value */
            hash: string;
            /** @description Template shape version. When omitted, the verifier resolves the version from the signature proof context. */
            templateVersion?: number;
        };
        hashGroup: {
            /** @description hex representation of the hash group hash value */
            hash: string;
            /** @description list of fields by order they appear in the hash group */
            fields: components["schemas"]["field"][];
        };
        /** @description describing a field in the hash group */
        field: {
            /** @description name of field */
            name: string;
            /**
             * @description type of field
             * @enum {string}
             */
            type: "string" | "int" | "bytes";
            /** @description hex representation of the field value */
            value: string;
        };
        EIP712Domain: {
            name?: string;
            version?: string;
            /** Format: uint64 */
            chainId?: number;
            /** Format: address */
            verifyingContract?: string;
        };
        EIP712TypedValue: RecursiveEIP712TypedValue;
        EIP712Types: {
            definitions?: components["schemas"]["EIP712TypeDefinition"][];
        };
        EIP712TypeDefinition: {
            name?: string;
            fields?: components["schemas"]["EIP712FieldDefinition"][];
        };
        EIP712FieldDefinition: {
            name?: string;
            type?: string;
        };
        EIP712Template: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "EIP712";
            domain: components["schemas"]["EIP712Domain"];
            message: {
                [key: string]: components["schemas"]["EIP712TypedValue"];
            };
            types: components["schemas"]["EIP712Types"];
            primaryType: string;
            /** @description hex representation of template hash */
            hash: string;
            /** @description Template shape version. When omitted, the verifier resolves the version from the signature proof context. */
            templateVersion?: number;
        };
        EIP712TypeString: string;
        EIP712TypeByte: string;
        EIP712TypeInteger: number;
        EIP712TypeBool: boolean;
        EIP712TypeObject: RecursiveEIP712TypeObject;
        EIP712TypeArray: RecursiveEIP712TypeArray;
        /**
         * @description hash function types
         * @enum {string}
         */
        hashFunction: "unspecified" | "sha3_256" | "sha3-256" | "blake2b" | "keccak_256" | "keccak-256";
        receipt: {
            /** @description the receipt id */
            id: string;
            /** @description How many units of the asset tokens */
            quantity: string;
            /**
             * Format: int64
             * @description transaction timestamp
             */
            timestamp: number;
            source?: components["schemas"]["account"];
            destination?: components["schemas"]["account"];
            transactionDetails?: components["schemas"]["transactionDetails"];
            operationType?: components["schemas"]["operationType"];
            tradeDetails: components["schemas"]["receiptTradeDetails"];
            proof?: components["schemas"]["proofPolicy"];
        };
        /** @description additional proof information attached to a receipt */
        proofPolicy: components["schemas"]["signatureProofPolicy"] | components["schemas"]["noProofPolicy"];
        /** @description no proof validation required for this policy */
        noProofPolicy: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "noProofPolicy";
        };
        signatureProofPolicy: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "signatureProofPolicy";
            signature?: components["schemas"]["signature"];
        };
        /** @description additional ledger specific */
        transactionDetails: {
            /** @description The Transaction id on the underlying ledger */
            transactionId: string;
            /** @description The Operation id */
            operationId?: string;
        };
        /** @enum {string} */
        operationType: "issue" | "transfer" | "hold" | "release" | "redeem" | "move";
        ledgerAssetInfo: {
            ledgerIdentifier: components["schemas"]["ledgerAssetIdentifier"];
            ledgerReference?: components["schemas"]["contractDetails"];
        };
        contractDetails: {
            /**
             * @description the type of the identifier (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            type: "contractDetails";
            /** @description the address */
            address: string;
            /** @description The standard of the token (e.g., ERC20, ERC721) */
            TokenStandard?: string;
            additionalContractDetails?: components["schemas"]["finP2PEVMOperatorDetails"];
        };
        finP2PEVMOperatorDetails: {
            /** @description The FinP2P Operator Contract Address */
            FinP2POperatorContractAddress?: string;
            /** @description Indicates if allowance is required */
            allowanceRequired?: boolean;
        };
        ledgerAssetBinding: components["schemas"]["ledgerAssetIdentifier"];
        AssetBalanceInfoRequest: {
            account: components["schemas"]["assetBalanceAccount"];
            asset: components["schemas"]["asset"];
            marker?: components["schemas"]["balanceMarker"];
        };
        assetBalanceAccount: components["schemas"]["finIdAccountBase"];
        /** @description marker of balance to denote the balance as of marker */
        balanceMarker: components["schemas"]["balanceMarkerTimestamp"] | components["schemas"]["balanceMarkerTransactionBlock"];
        balanceMarkerTimestamp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "timestamp";
            /**
             * Format: int64
             * @description epoch timestamp in seconds
             */
            timestamp: number;
        };
        balanceMarkerTransactionBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "transactionBlock";
            /** Format: int64 */
            blockNumber: number;
            transaction: string;
        };
        AssetBalanceInfoResponse: {
            account: components["schemas"]["assetBalanceAccount"];
            asset: components["schemas"]["asset"];
            balanceInfo?: components["schemas"]["assetBalance"];
        };
        assetBalance: {
            asset: components["schemas"]["asset"];
            /**
             * Format: ^-?\d+(\.\d+)?$
             * @description The total amount currently in or owed by the account
             */
            current: string;
            /**
             * Format: ^-?\d+(\.\d+)?$
             * @description The amount immediately usable from the account
             */
            available: string;
            /**
             * Format: ^-?\d+(\.\d+)?$
             * @description The amount pending or on hold within the account
             */
            held: string;
            /** @description list of receipt associated with the balance info */
            receipts?: components["schemas"]["receipt"][];
        };
        ApproveExecutionPlanRequest: {
            /** @description execution plan information */
            executionPlan: {
                /** @description execution plan id */
                id: string;
            };
        };
        randomPollingInterval: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "random";
        };
        absolutePollingInterval: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "absolute";
            /** @description absolute time as epoch time seconds */
            time: number;
        };
        relativePollingInterval: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "relative";
            /**
             * @description ISO-8601 duration format
             * @example PT5M (5Min duration), P1DT30M (1 Day and 30 Minutes )
             */
            duration: string;
        };
        pollingResultsStrategy: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "poll";
            polling: components["schemas"]["randomPollingInterval"] | components["schemas"]["absolutePollingInterval"] | components["schemas"]["relativePollingInterval"];
        };
        callbackEndpoint: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "endpoint";
        };
        callbackResultsStrategy: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "callback";
            callback: components["schemas"]["callbackEndpoint"];
        };
        /** @description additional metadata regarding the operation */
        OperationMetadata: {
            /**
             * @description denote the expected response strategy of the operation, i.e. how would completion and results of the operation should be handled
             *     optional, if not provided [polling strategy](#/components/schema/pollingResultsStrategy) will be use with [random interval](#/components/schema/randomPollingInterval)
             */
            operationResponseStrategy?: components["schemas"]["pollingResultsStrategy"] | components["schemas"]["callbackResultsStrategy"];
        };
        OperationBase: {
            /** @description unique correlation id which identify the operation */
            cid: string;
            /**
             * @description flag indicating if the operation completed, if true then error or response must be present (but not both)
             * @default false
             */
            isCompleted: boolean;
            operationMetadata?: components["schemas"]["OperationMetadata"];
        };
        PlanApproved: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "approved";
        };
        ValidationFailure: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            failureType: "validationFailure";
            /**
             * Format: uint32
             * @description ledger error code for validation
             */
            code: number;
            message: string;
        };
        RegulationError: {
            /** @description the type of regulation */
            regulationType: string;
            /** @description actionable details of the error */
            details: string;
        };
        RegulationFailure: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            failureType: "regulationFailure";
            errors: components["schemas"]["RegulationError"][];
        };
        PlanRejected: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "rejected";
            failure?: components["schemas"]["ValidationFailure"] | components["schemas"]["RegulationFailure"];
        };
        PlanApprovalResponse: {
            approval?: components["schemas"]["PlanApproved"] | components["schemas"]["PlanRejected"];
        };
        ExecutionPlanApprovalOperation: components["schemas"]["OperationBase"] & components["schemas"]["PlanApprovalResponse"];
        ApproveExecutionPlanResponse: components["schemas"]["ExecutionPlanApprovalOperation"];
        APIError: {
            /** @description Error code indicating the specific failure - for more information see [API Errors](./api-error-codes-reference). */
            code: number;
            /** @description A descriptive message providing context about the error. */
            message: string;
        };
        APIErrors: {
            errors: components["schemas"]["APIError"][];
        };
        executionPlanCancellationProposal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            proposalType: "cancel";
        };
        executionPlanResetProposal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            proposalType: "reset";
            /**
             * Format: uint32
             * @description sequence number of the instruction to reset and retry in the execution plan
             */
            proposedSequence: number;
        };
        executionPlanInstructionProposal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            proposalType: "instruction";
            /**
             * Format: uint32
             * @description sequence number of the instruction completion event
             */
            instructionSequence: number;
        };
        executionPlanProposalRequest: {
            /** @description execution plan information */
            executionPlan: {
                /** @description execution plan id */
                id: string;
                /** @description type of proposal payload */
                proposal: components["schemas"]["executionPlanCancellationProposal"] | components["schemas"]["executionPlanInstructionProposal"] | components["schemas"]["executionPlanResetProposal"];
            };
        };
        /** @description provides status update on the agreement reached for a specific proposal */
        executionPlanProposalStatusRequest: {
            /** @enum {string} */
            status: "approved" | "rejected";
            request: components["schemas"]["executionPlanProposalRequest"];
        };
        /**
         * Format: finid
         * @description Existing owner hex representation of a secp256k1 public key 33 bytes compressed
         */
        finId: string;
        finp2pAssetWithType: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "finp2p";
            /** @description unique resource ID of the FinP2P asset */
            resourceId: string;
        };
        customAsset: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "custom";
        };
        depositAsset: components["schemas"]["finp2pAssetWithType"] | components["schemas"]["customAsset"];
        /**
         * @description 32 bytes buffer (24 randomly generated bytes by the client + 8 bytes epoch timestamp seconds) encoded to hex:
         *
         *       const nonce = Buffer.alloc(32);
         *       nonce.fill(crypto.randomBytes(24), 0, 24);
         *
         *       const nowEpochSeconds = Math.floor(new Date().getTime() / 1000);
         *       const t = BigInt(nowEpochSeconds);
         *       nonce.writeBigInt64BE(t, 24);
         */
        nonce: string;
        ibanAccountDetails: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "iban";
            iban: string;
        };
        swiftAccountDetails: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "swift";
            swiftCode: string;
            accountNumber: string;
        };
        sortCodeDetails: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sortCode";
            /** @description sort code has XX-XX-XX format */
            code: string;
            accountNumber: string;
        };
        wireDetails: components["schemas"]["ibanAccountDetails"] | components["schemas"]["swiftAccountDetails"] | components["schemas"]["sortCodeDetails"];
        wireTransfer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "wireTransfer";
            accountHolderName: string;
            bankName: string;
            wireDetails: components["schemas"]["wireDetails"];
            line1?: string;
            city?: string;
            postalCode?: string;
            country?: string;
        };
        wireTransferUSA: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "wireTransferUSA";
            accountNumber: string;
            routingNumber: string;
            line1?: string;
            city?: string;
            postalCode?: string;
            country?: string;
            state?: string;
        };
        cryptoTransfer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cryptoTransfer";
            network: string;
            contractAddress: string;
            walletAddress: string;
        };
        paymentInstructions: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "paymentInstructions";
            instruction: string;
        };
        paymentMethod: {
            description: string;
            /** @description accepted currency for payment */
            currency: string;
            methodInstruction: components["schemas"]["wireTransfer"] | components["schemas"]["wireTransferUSA"] | components["schemas"]["cryptoTransfer"] | components["schemas"]["paymentInstructions"];
        };
        paymentMethods: components["schemas"]["paymentMethod"][];
        /**
         * @description finp2p resource id format
         * @example bank-x:101:9929ccaf-8967-4ba3-9198-a4b8e3128388
         */
        resourceId: string;
        "ledgerAssetIdentifierTypeCAIP-19": {
            /**
             * @description Classification type standards (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            assetIdentifierType: "CAIP-19";
            network?: string;
            tokenId: string;
            standard?: string;
        };
        ledgerAssetIdentifier: components["schemas"]["ledgerAssetIdentifierTypeCAIP-19"];
        /** @description describes asset information */
        finp2pAsset: {
            id: components["schemas"]["resourceId"];
            ledgerIdentifier: components["schemas"]["ledgerAssetIdentifier"];
        };
        finp2pAssetBase: {
            /** @description unique resource ID of the FinP2P asset */
            resourceId: string;
        };
        walletAccount: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "walletAccount";
            /** @description address of the wallet */
            address: string;
        };
        caip10Account: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "caip10Account";
            /** @description CAIP-2 chain_id, e.g. "eip155:1", "solana:5eykt4...", "hedera:mainnet" (the same token used by the CAIP-19 asset identifier network) */
            network: string;
            /** @description CAIP-10 account_address (chain-native address) */
            address: string;
        };
        custodialAccount: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "custodialAccount";
            /** @description Custody provider discriminator, e.g. "fireblocks" */
            provider: string;
            /** @description Provider-internal account identifier (e.g. a Fireblocks vault account id) */
            vaultAccountId: string;
            /** @description Optional. Narrows the custodial account to a specific asset/chain. */
            assetId?: string;
        };
        receiptExecutionContext: {
            executionPlanId: string;
            instructionSequenceNumber: number;
        };
        receiptTradeDetails: {
            intentId?: string;
            intentVersion?: string;
            executionContext?: components["schemas"]["receiptExecutionContext"];
        };
        /** @description The name of the asset */
        assetName: string;
        /**
         * @description Owner resource id
         * @example bank-x:101:511c1d7f-4ed8-410d-887c-a10e3e499a01
         */
        ownerResourceId: string;
        /**
         * @description Indicates how the asset is denominated
         * @enum {string}
         */
        assetDenominationType: "finp2p" | "fiat" | "cryptocurrency";
        assetDenomination: {
            type: components["schemas"]["assetDenominationType"];
            /** @description Unique code identifying the denomination asset type */
            code: string;
        };
        noneAccount: Record<string, never>;
        networkAccount: components["schemas"]["walletAccount"] | components["schemas"]["caip10Account"] | components["schemas"]["custodialAccount"] | components["schemas"]["noneAccount"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    approveExecutionPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ApproveExecutionPlanRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveExecutionPlanResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    executionPlanProposal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["executionPlanProposalRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveExecutionPlanResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    executionPlanProposalStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["executionPlanProposalStatusRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description successful operation */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    depositInstruction: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DepositInstructionRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepositInstructionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    payout: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PayoutRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    getAssetBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GetAssetBalanceRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAssetBalanceResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1100,
                     *           "message": "Resource not found"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    createAsset: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateAssetRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAssetResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    issueAssets: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IssueAssetsRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueAssetsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    redeemAssets: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RedeemAssetsRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemAssetsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    moveAssets: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MoveAssetsRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveAssetsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    transferAsset: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TransferAssetRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferAssetResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Challenge will be issued asynchronously; poll `/operations/status/{cid}`. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOperationAccepted"];
                };
            };
            /** @description Challenge issued immediately as part of the response. */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOperationChallenge"];
                };
            };
        };
    };
    submitAccountProof: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Correlation id of the account workflow. */
                cid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAccountProofRequest"];
            };
        };
        responses: {
            /** @description Proof accepted; verification continues per response strategy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOperationAccepted"];
                };
            };
        };
    };
    removeAccount: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path: {
                /** @description LA-assigned account identifier. */
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOperationAccepted"];
                };
            };
        };
    };
    getReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of the asset transaction */
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetReceiptResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1100,
                     *           "message": "Resource not found"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    holdOperation: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["HoldOperationRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldOperationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1100,
                     *           "message": "Resource not found"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    releaseOperation: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReleaseOperationRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseOperationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    rollbackOperation: {
        parameters: {
            query?: never;
            header: {
                /** @description hex encoding of a 32-byte payload consisting of 24 random bytes + 8-byte epoch timestamp (seconds) */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RollbackOperationRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RollbackOperationResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    getOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description correlation id of an operation */
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOperationStatusResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1100,
                     *           "message": "Resource not found"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    GetAssetBalanceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetBalanceInfoRequest"];
            };
        };
        responses: {
            /** @description successful operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetBalanceInfoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1002,
                     *           "message": "Invalid request format"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 1100,
                     *           "message": "Resource not found"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "errors": [
                     *         {
                     *           "code": 2202,
                     *           "message": "Internal service failure"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["APIErrors"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
            /** @description Service is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example unavailable */
                        status?: string;
                    };
                };
            };
        };
    };
}
